--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with Interfaces;
with PolyORB_HI.Port_Type_Marshallers;
with PolyORB_HI.Utils;
with PolyORB_HI_Generated.Activity;
use PolyORB_HI_Generated.Activity;
with Ada.Real_Time;
with PolyORB_HI.Time_Marshallers;
with PolyORB_HI_Generated.Marshallers;

package body PolyORB_HI_Generated.Transport is

  procedure satellite_sys_alt_reader_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure satellite_sys_alt_controller_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure satellite_sys_photo_send_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  procedure satellite_sys_photo_trigger_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  -------------
  -- Deliver -- 
  -------------

  procedure Deliver
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : PolyORB_HI.Messages.Message_Type;
    Value : Interfaces.Unsigned_16;
    Port : PolyORB_HI_Generated.Deployment.Port_Type;
    use type PolyORB_HI.Streams.Stream_Element_Offset;
  begin
    PolyORB_HI.Messages.Write
     (Msg,
      Message
       ((Message'First
          + PolyORB_HI.Messages.Header_Size) .. Message'Last));
    PolyORB_HI.Port_Type_Marshallers.Unmarshall
     (Value,
      Msg);
    Port :=
     PolyORB_HI.Utils.Corresponding_Port
       (Value);
    if (Entity
      = PolyORB_HI_Generated.Deployment.controller_process_alt_reader_K)
    then
      satellite_sys_alt_reader_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K)
    then
      satellite_sys_alt_controller_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.controller_process_photo_send_K)
    then
      satellite_sys_photo_send_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    elsif (Entity
      = PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_K)
    then
      satellite_sys_photo_trigger_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    end if;
  end Deliver;

  function satellite_sys_alt_reader_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  function satellite_sys_alt_controller_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  function satellite_sys_photo_send_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  function satellite_sys_photo_trigger_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind;

  ----------
  -- Send -- 
  ----------

  function Send
   (From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Messages.Message_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : constant PolyORB_HI.Streams.Stream_Element_Array :=
     PolyORB_HI.Messages.Encapsulate
       (Message,
        From,
        Entity);
  begin
    if (From
      = PolyORB_HI_Generated.Deployment.controller_process_alt_reader_K)
    then
      return satellite_sys_alt_reader_Send
       (Entity,
        Msg);
    elsif (From
      = PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K)
    then
      return satellite_sys_alt_controller_Send
       (Entity,
        Msg);
    elsif (From
      = PolyORB_HI_Generated.Deployment.controller_process_photo_send_K)
    then
      return satellite_sys_photo_send_Send
       (Entity,
        Msg);
    elsif (From
      = PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_K)
    then
      return satellite_sys_photo_trigger_Send
       (Entity,
        Msg);
    else
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_Transport);
    end if;
  end Send;

  --------------------------------------
  -- satellite_sys_alt_reader_Deliver -- 
  --------------------------------------

  procedure satellite_sys_alt_reader_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : satellite_sys_read_altitude_impl_Interface;
    Time_Stamp_Ü : Ada.Real_Time.Time;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.controller_process_alt_reader_alt_in_K)
    then
      PolyORB_HI.Time_Marshallers.Unmarshall
       (Time_Stamp_Ü,
        Msg);
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (alt_in,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.controller_process_alt_reader_K,
        Thread_Interface_Ü,
        From,
        Time_Stamp_Ü);
    end if;
  end satellite_sys_alt_reader_Deliver;

  -----------------------------------
  -- satellite_sys_alt_reader_Send -- 
  -----------------------------------

  function satellite_sys_alt_reader_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
    use PolyORB_HI_Generated.Deployment;
  begin
    if (Entity
      = PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K)
    then
      Deliver
       (Entity,
        Message);
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_None);
    else
      return PolyORB_HI.Errors.Error_Kind'
       (PolyORB_HI.Errors.Error_Transport);
    end if;
  end satellite_sys_alt_reader_Send;

  ------------------------------------------
  -- satellite_sys_alt_controller_Deliver -- 
  ------------------------------------------

  procedure satellite_sys_alt_controller_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : satellite_sys_altitude_controll_impl_Interface;
    Time_Stamp_Ü : Ada.Real_Time.Time;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.controller_process_alt_controller_alt_in_K)
    then
      PolyORB_HI.Time_Marshallers.Unmarshall
       (Time_Stamp_Ü,
        Msg);
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (alt_in,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K,
        Thread_Interface_Ü,
        From,
        Time_Stamp_Ü);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.controller_process_alt_controller_toggle_manual_control_K)
    then
      PolyORB_HI.Time_Marshallers.Unmarshall
       (Time_Stamp_Ü,
        Msg);
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (toggle_manual_control,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K,
        Thread_Interface_Ü,
        From,
        Time_Stamp_Ü);
    elsif (Port
      = PolyORB_HI_Generated.Deployment.controller_process_alt_controller_manual_controls_K)
    then
      PolyORB_HI.Time_Marshallers.Unmarshall
       (Time_Stamp_Ü,
        Msg);
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (manual_controls,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K,
        Thread_Interface_Ü,
        From,
        Time_Stamp_Ü);
    end if;
  end satellite_sys_alt_controller_Deliver;

  ---------------------------------------
  -- satellite_sys_alt_controller_Send -- 
  ---------------------------------------

  function satellite_sys_alt_controller_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
  begin
    --  Device
    --  Device
    --  Device
    --  Device
    --  Device
    --  Device
    --  Device
    return PolyORB_HI.Errors.Error_Kind'
     (PolyORB_HI.Errors.Error_Transport);
  end satellite_sys_alt_controller_Send;

  --------------------------------------
  -- satellite_sys_photo_send_Deliver -- 
  --------------------------------------

  procedure satellite_sys_photo_send_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : satellite_sys_send_photo_impl_Interface;
    Time_Stamp_Ü : Ada.Real_Time.Time;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.controller_process_photo_send_photo_in_K)
    then
      PolyORB_HI.Time_Marshallers.Unmarshall
       (Time_Stamp_Ü,
        Msg);
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (photo_in,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.controller_process_photo_send_K,
        Thread_Interface_Ü,
        From,
        Time_Stamp_Ü);
    end if;
  end satellite_sys_photo_send_Deliver;

  -----------------------------------
  -- satellite_sys_photo_send_Send -- 
  -----------------------------------

  function satellite_sys_photo_send_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
  begin
    --  Device
    return PolyORB_HI.Errors.Error_Kind'
     (PolyORB_HI.Errors.Error_Transport);
  end satellite_sys_photo_send_Send;

  -----------------------------------------
  -- satellite_sys_photo_trigger_Deliver -- 
  -----------------------------------------

  procedure satellite_sys_photo_trigger_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : satellite_sys_get_photo_impl_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_photo_trigger_in_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (photo_trigger_in,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_K,
        Thread_Interface_Ü,
        From);
    end if;
  end satellite_sys_photo_trigger_Deliver;

  --------------------------------------
  -- satellite_sys_photo_trigger_Send -- 
  --------------------------------------

  function satellite_sys_photo_trigger_Send
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Warnings
     (Off,
      Message);
    pragma Warnings
     (Off,
      Entity);
  begin
    --  Device
    return PolyORB_HI.Errors.Error_Kind'
     (PolyORB_HI.Errors.Error_Transport);
  end satellite_sys_photo_trigger_Send;

end PolyORB_HI_Generated.Transport;
