--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Port_Kinds;
with System;
with PolyORB_HI_Generated.Marshallers;
with PolyORB_HI_Generated.Transport;
with PolyORB_HI.Thread_Interrogators;
pragma Elaborate_All (PolyORB_HI.Thread_Interrogators);
with PolyORB_HI_Generated.Subprograms;

package body PolyORB_HI_Generated.Activity is

  --  BEGIN: Data types used by all instances of component read_altitude.impl

  type satellite_sys_read_altitude_impl_Integer_Array is
   array (satellite_sys_read_altitude_impl_Port_Type)
     of Standard.Integer;

  type satellite_sys_read_altitude_impl_Port_Kind_Array is
   array (satellite_sys_read_altitude_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Controller_Process_1_Max_Port_Image_Size is
   Integer range 1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size;

  subtype UT_Activity_Controller_Process_satellite_sys_read_altitude_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Controller_Process_1_Max_Port_Image_Size);

  type satellite_sys_read_altitude_impl_Port_Image_Array is
   array (satellite_sys_read_altitude_impl_Port_Type)
     of UT_Activity_Controller_Process_satellite_sys_read_altitude_impl_Port_Image_Array_Component;

  type satellite_sys_read_altitude_impl_Address_Array is
   array (satellite_sys_read_altitude_impl_Port_Type)
     of System.Address;

  type satellite_sys_read_altitude_impl_Overflow_Protocol_Array is
   array (satellite_sys_read_altitude_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component read_altitude.impl

  satellite_sys_alt_reader_Port_Kinds : constant satellite_sys_read_altitude_impl_Port_Kind_Array :=
   (alt_in =>
     PolyORB_HI.Port_Kinds.In_Data_Port,
    alt_out =>
     PolyORB_HI.Port_Kinds.Out_Data_Port);

  satellite_sys_alt_reader_Port_Images : constant satellite_sys_read_altitude_impl_Port_Image_Array :=
   (alt_in =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_reader_alt_in_K),
    alt_out =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_reader_alt_out_K));

  satellite_sys_alt_reader_FIFO_Sizes : constant satellite_sys_read_altitude_impl_Integer_Array :=
   (alt_in =>
     1,
    alt_out =>
     -1);

  satellite_sys_alt_reader_Offsets : constant satellite_sys_read_altitude_impl_Integer_Array :=
   (alt_in =>
     1,
    alt_out =>
     0);

  satellite_sys_alt_reader_Overflow_Protocols : constant satellite_sys_read_altitude_impl_Overflow_Protocol_Array :=
   (alt_in =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    alt_out =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  satellite_sys_alt_reader_Urgencies : constant satellite_sys_read_altitude_impl_Integer_Array :=
   (alt_in =>
     0,
    alt_out =>
     0);

  satellite_sys_alt_reader_Total_FIFO_Size : constant Standard.Integer :=
   1;

  type UT_Activity_Controller_Process_alt_reader_alt_out_Destinations_Array is
   array (Standard.Positive range <>)
     of PolyORB_HI_Generated.Deployment.Port_Type;

  alt_reader_alt_out_Destinations : constant UT_Activity_Controller_Process_alt_reader_alt_out_Destinations_Array :=
   UT_Activity_Controller_Process_alt_reader_alt_out_Destinations_Array'
     (1 =>
       PolyORB_HI_Generated.Deployment.controller_process_alt_controller_alt_in_K);

  satellite_sys_alt_reader_N_Destinations : constant satellite_sys_read_altitude_impl_Integer_Array :=
   (alt_in =>
     0,
    alt_out =>
     1);

  alt_reader_Destinations : constant satellite_sys_read_altitude_impl_Address_Array :=
   (alt_in =>
     System.null_Address,
    alt_out =>
     alt_reader_alt_out_Destinations'Address);

  package satellite_sys_alt_reader_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => satellite_sys_read_altitude_impl_Port_Type,
      Integer_Array => satellite_sys_read_altitude_impl_Integer_Array,
      Port_Kind_Array => satellite_sys_read_altitude_impl_Port_Kind_Array,
      Port_Image_Array => satellite_sys_read_altitude_impl_Port_Image_Array,
      Address_Array => satellite_sys_read_altitude_impl_Address_Array,
      Overflow_Protocol_Array => satellite_sys_read_altitude_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => satellite_sys_read_altitude_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.controller_process_alt_reader_K,
      Thread_Port_Kinds => satellite_sys_alt_reader_Port_Kinds,
      Has_Event_Ports => False,
      Thread_Port_Images => satellite_sys_alt_reader_Port_Images,
      Thread_Fifo_Sizes => satellite_sys_alt_reader_FIFO_Sizes,
      Thread_Fifo_Offsets => satellite_sys_alt_reader_Offsets,
      Thread_Overflow_Protocols => satellite_sys_alt_reader_Overflow_Protocols,
      Urgencies => satellite_sys_alt_reader_Urgencies,
      Global_Data_Queue_Size => satellite_sys_alt_reader_Total_FIFO_Size,
      N_Destinations => satellite_sys_alt_reader_N_Destinations,
      Destinations => alt_reader_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => satellite_sys_alt_reader_Task.Next_Deadline);

  --  Periodic task : alt_reader

  ----------------------------------
  -- satellite_sys_alt_reader_Job -- 
  ----------------------------------

  function satellite_sys_alt_reader_Job return PolyORB_HI.Errors.Error_Kind is
    alt_in_V : PolyORB_HI_Generated.Types.mov_data;
    alt_out_V : PolyORB_HI_Generated.Types.mov_data;
    Error_Ü : PolyORB_HI.Errors.Error_Kind;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    if (satellite_sys_alt_reader_Interrogators.Get_Count
     (alt_in)
      /= -1)
    then
      alt_in_V :=
       satellite_sys_alt_reader_Interrogators.Get_Value
         (alt_in).alt_in_DATA;
    else
      alt_in_V :=
       PolyORB_HI_Generated.Types.mov_data_Default_Value;
    end if;
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.satellite_sys_read_altitude_spg
     (alt_in => alt_in_V,
      alt_out => alt_out_V);
    --  Set the call sequence OUT port values
    satellite_sys_alt_reader_Interrogators.Put_Value
     (satellite_sys_read_altitude_impl_Interface'
       (Port => alt_out,
        alt_out_DATA => alt_out_V));
    --  Send the call sequence OUT port values
    Error_Ü :=
     satellite_sys_alt_reader_Interrogators.Send_Output
       (alt_out);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    --  Return error code
    return Error_Ü;
  end satellite_sys_alt_reader_Job;

  --  BEGIN: Data types used by all instances of component 
  --  altitude_controll.impl

  type satellite_sys_altitude_controll_impl_Integer_Array is
   array (satellite_sys_altitude_controll_impl_Port_Type)
     of Standard.Integer;

  type satellite_sys_altitude_controll_impl_Port_Kind_Array is
   array (satellite_sys_altitude_controll_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Controller_Process_satellite_sys_altitude_controll_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Controller_Process_1_Max_Port_Image_Size);

  type satellite_sys_altitude_controll_impl_Port_Image_Array is
   array (satellite_sys_altitude_controll_impl_Port_Type)
     of UT_Activity_Controller_Process_satellite_sys_altitude_controll_impl_Port_Image_Array_Component;

  type satellite_sys_altitude_controll_impl_Address_Array is
   array (satellite_sys_altitude_controll_impl_Port_Type)
     of System.Address;

  type satellite_sys_altitude_controll_impl_Overflow_Protocol_Array is
   array (satellite_sys_altitude_controll_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component 
  --  altitude_controll.impl

  satellite_sys_alt_controller_Port_Kinds : constant satellite_sys_altitude_controll_impl_Port_Kind_Array :=
   (alt_in =>
     PolyORB_HI.Port_Kinds.In_Data_Port,
    engine_1_control =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    engine_2_control =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    engine_3_control =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    engine_4_control =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    engine_5_control =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    engine_6_control =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    rotation =>
     PolyORB_HI.Port_Kinds.Out_Data_Port,
    toggle_manual_control =>
     PolyORB_HI.Port_Kinds.In_Data_Port,
    manual_controls =>
     PolyORB_HI.Port_Kinds.In_Data_Port);

  satellite_sys_alt_controller_Port_Images : constant satellite_sys_altitude_controll_impl_Port_Image_Array :=
   (alt_in =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_alt_in_K),
    engine_1_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_engine_1_control_K),
    engine_2_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_engine_2_control_K),
    engine_3_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_engine_3_control_K),
    engine_4_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_engine_4_control_K),
    engine_5_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_engine_5_control_K),
    engine_6_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_engine_6_control_K),
    rotation =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_rotation_K),
    toggle_manual_control =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_toggle_manual_control_K),
    manual_controls =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_alt_controller_manual_controls_K));

  satellite_sys_alt_controller_FIFO_Sizes : constant satellite_sys_altitude_controll_impl_Integer_Array :=
   (alt_in =>
     1,
    engine_1_control =>
     -1,
    engine_2_control =>
     -1,
    engine_3_control =>
     -1,
    engine_4_control =>
     -1,
    engine_5_control =>
     -1,
    engine_6_control =>
     -1,
    rotation =>
     -1,
    toggle_manual_control =>
     1,
    manual_controls =>
     1);

  satellite_sys_alt_controller_Offsets : constant satellite_sys_altitude_controll_impl_Integer_Array :=
   (alt_in =>
     1,
    engine_1_control =>
     0,
    engine_2_control =>
     0,
    engine_3_control =>
     0,
    engine_4_control =>
     0,
    engine_5_control =>
     0,
    engine_6_control =>
     0,
    rotation =>
     0,
    toggle_manual_control =>
     2,
    manual_controls =>
     3);

  satellite_sys_alt_controller_Overflow_Protocols : constant satellite_sys_altitude_controll_impl_Overflow_Protocol_Array :=
   (alt_in =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    engine_1_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    engine_2_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    engine_3_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    engine_4_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    engine_5_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    engine_6_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    rotation =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    toggle_manual_control =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    manual_controls =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  satellite_sys_alt_controller_Urgencies : constant satellite_sys_altitude_controll_impl_Integer_Array :=
   (alt_in =>
     0,
    engine_1_control =>
     0,
    engine_2_control =>
     0,
    engine_3_control =>
     0,
    engine_4_control =>
     0,
    engine_5_control =>
     0,
    engine_6_control =>
     0,
    rotation =>
     0,
    toggle_manual_control =>
     0,
    manual_controls =>
     0);

  satellite_sys_alt_controller_Total_FIFO_Size : constant Standard.Integer :=
   3;

  satellite_sys_alt_controller_N_Destinations : constant satellite_sys_altitude_controll_impl_Integer_Array :=
   (alt_in =>
     0,
    engine_1_control =>
     0,
    engine_2_control =>
     0,
    engine_3_control =>
     0,
    engine_4_control =>
     0,
    engine_5_control =>
     0,
    engine_6_control =>
     0,
    rotation =>
     0,
    toggle_manual_control =>
     0,
    manual_controls =>
     0);

  alt_controller_Destinations : constant satellite_sys_altitude_controll_impl_Address_Array :=
   (alt_in =>
     System.null_Address,
    engine_1_control =>
     System.null_Address,
    engine_2_control =>
     System.null_Address,
    engine_3_control =>
     System.null_Address,
    engine_4_control =>
     System.null_Address,
    engine_5_control =>
     System.null_Address,
    engine_6_control =>
     System.null_Address,
    rotation =>
     System.null_Address,
    toggle_manual_control =>
     System.null_Address,
    manual_controls =>
     System.null_Address);

  package satellite_sys_alt_controller_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => satellite_sys_altitude_controll_impl_Port_Type,
      Integer_Array => satellite_sys_altitude_controll_impl_Integer_Array,
      Port_Kind_Array => satellite_sys_altitude_controll_impl_Port_Kind_Array,
      Port_Image_Array => satellite_sys_altitude_controll_impl_Port_Image_Array,
      Address_Array => satellite_sys_altitude_controll_impl_Address_Array,
      Overflow_Protocol_Array => satellite_sys_altitude_controll_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => satellite_sys_altitude_controll_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.controller_process_alt_controller_K,
      Thread_Port_Kinds => satellite_sys_alt_controller_Port_Kinds,
      Has_Event_Ports => False,
      Thread_Port_Images => satellite_sys_alt_controller_Port_Images,
      Thread_Fifo_Sizes => satellite_sys_alt_controller_FIFO_Sizes,
      Thread_Fifo_Offsets => satellite_sys_alt_controller_Offsets,
      Thread_Overflow_Protocols => satellite_sys_alt_controller_Overflow_Protocols,
      Urgencies => satellite_sys_alt_controller_Urgencies,
      Global_Data_Queue_Size => satellite_sys_alt_controller_Total_FIFO_Size,
      N_Destinations => satellite_sys_alt_controller_N_Destinations,
      Destinations => alt_controller_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => satellite_sys_alt_controller_Task.Next_Deadline);

  --  Periodic task : alt_controller

  --------------------------------------
  -- satellite_sys_alt_controller_Job -- 
  --------------------------------------

  function satellite_sys_alt_controller_Job return PolyORB_HI.Errors.Error_Kind is
    alt_in_V : PolyORB_HI_Generated.Types.mov_data;
    toggle_manual_control_V : PolyORB_HI_Generated.Types.toggle_data;
    manual_controls_V : PolyORB_HI_Generated.Types.Satellite_Controls_impl;
    engine_1_control_V : PolyORB_HI_Generated.Types.toggle_data;
    engine_2_control_V : PolyORB_HI_Generated.Types.toggle_data;
    engine_3_control_V : PolyORB_HI_Generated.Types.toggle_data;
    engine_4_control_V : PolyORB_HI_Generated.Types.toggle_data;
    engine_5_control_V : PolyORB_HI_Generated.Types.toggle_data;
    engine_6_control_V : PolyORB_HI_Generated.Types.toggle_data;
    rotation_V : PolyORB_HI_Generated.Types.mov_data;
    Error_Ü : PolyORB_HI.Errors.Error_Kind;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    if (satellite_sys_alt_controller_Interrogators.Get_Count
     (alt_in)
      /= -1)
    then
      alt_in_V :=
       satellite_sys_alt_controller_Interrogators.Get_Value
         (alt_in).alt_in_DATA;
    else
      alt_in_V :=
       PolyORB_HI_Generated.Types.mov_data_Default_Value;
    end if;
    if (satellite_sys_alt_controller_Interrogators.Get_Count
     (toggle_manual_control)
      /= -1)
    then
      toggle_manual_control_V :=
       satellite_sys_alt_controller_Interrogators.Get_Value
         (toggle_manual_control).toggle_manual_control_DATA;
    else
      toggle_manual_control_V :=
       PolyORB_HI_Generated.Types.toggle_data_Default_Value;
    end if;
    if (satellite_sys_alt_controller_Interrogators.Get_Count
     (manual_controls)
      /= -1)
    then
      manual_controls_V :=
       satellite_sys_alt_controller_Interrogators.Get_Value
         (manual_controls).manual_controls_DATA;
    else
      manual_controls_V :=
       PolyORB_HI_Generated.Types.Satellite_Controls_impl_Default_Value;
    end if;
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.satellite_sys_alt_controll_spg
     (alt_in => alt_in_V,
      toggle_manual_control => toggle_manual_control_V,
      manual_controls => manual_controls_V,
      eng1Out => engine_1_control_V,
      eng2Out => engine_2_control_V,
      eng3Out => engine_3_control_V,
      eng4Out => engine_4_control_V,
      eng5Out => engine_5_control_V,
      eng6Out => engine_6_control_V,
      rotation => rotation_V);
    --  Set the call sequence OUT port values
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => engine_1_control,
        engine_1_control_DATA => engine_1_control_V));
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => engine_2_control,
        engine_2_control_DATA => engine_2_control_V));
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => engine_3_control,
        engine_3_control_DATA => engine_3_control_V));
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => engine_4_control,
        engine_4_control_DATA => engine_4_control_V));
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => engine_5_control,
        engine_5_control_DATA => engine_5_control_V));
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => engine_6_control,
        engine_6_control_DATA => engine_6_control_V));
    satellite_sys_alt_controller_Interrogators.Put_Value
     (satellite_sys_altitude_controll_impl_Interface'
       (Port => rotation,
        rotation_DATA => rotation_V));
    --  Send the call sequence OUT port values
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (engine_1_control);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (engine_2_control);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (engine_3_control);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (engine_4_control);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (engine_5_control);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (engine_6_control);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    Error_Ü :=
     satellite_sys_alt_controller_Interrogators.Send_Output
       (rotation);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    --  Return error code
    return Error_Ü;
  end satellite_sys_alt_controller_Job;

  --  BEGIN: Data types used by all instances of component send_photo.impl

  type satellite_sys_send_photo_impl_Integer_Array is
   array (satellite_sys_send_photo_impl_Port_Type)
     of Standard.Integer;

  type satellite_sys_send_photo_impl_Port_Kind_Array is
   array (satellite_sys_send_photo_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Controller_Process_satellite_sys_send_photo_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Controller_Process_1_Max_Port_Image_Size);

  type satellite_sys_send_photo_impl_Port_Image_Array is
   array (satellite_sys_send_photo_impl_Port_Type)
     of UT_Activity_Controller_Process_satellite_sys_send_photo_impl_Port_Image_Array_Component;

  type satellite_sys_send_photo_impl_Address_Array is
   array (satellite_sys_send_photo_impl_Port_Type)
     of System.Address;

  type satellite_sys_send_photo_impl_Overflow_Protocol_Array is
   array (satellite_sys_send_photo_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component send_photo.impl

  satellite_sys_photo_send_Port_Kinds : constant satellite_sys_send_photo_impl_Port_Kind_Array :=
   (photo_in =>
     PolyORB_HI.Port_Kinds.In_Data_Port,
    photo_out =>
     PolyORB_HI.Port_Kinds.Out_Data_Port);

  satellite_sys_photo_send_Port_Images : constant satellite_sys_send_photo_impl_Port_Image_Array :=
   (photo_in =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_photo_send_photo_in_K),
    photo_out =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_photo_send_photo_out_K));

  satellite_sys_photo_send_FIFO_Sizes : constant satellite_sys_send_photo_impl_Integer_Array :=
   (photo_in =>
     1,
    photo_out =>
     -1);

  satellite_sys_photo_send_Offsets : constant satellite_sys_send_photo_impl_Integer_Array :=
   (photo_in =>
     1,
    photo_out =>
     0);

  satellite_sys_photo_send_Overflow_Protocols : constant satellite_sys_send_photo_impl_Overflow_Protocol_Array :=
   (photo_in =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    photo_out =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  satellite_sys_photo_send_Urgencies : constant satellite_sys_send_photo_impl_Integer_Array :=
   (photo_in =>
     0,
    photo_out =>
     0);

  satellite_sys_photo_send_Total_FIFO_Size : constant Standard.Integer :=
   1;

  satellite_sys_photo_send_N_Destinations : constant satellite_sys_send_photo_impl_Integer_Array :=
   (photo_in =>
     0,
    photo_out =>
     0);

  photo_send_Destinations : constant satellite_sys_send_photo_impl_Address_Array :=
   (photo_in =>
     System.null_Address,
    photo_out =>
     System.null_Address);

  package satellite_sys_photo_send_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => satellite_sys_send_photo_impl_Port_Type,
      Integer_Array => satellite_sys_send_photo_impl_Integer_Array,
      Port_Kind_Array => satellite_sys_send_photo_impl_Port_Kind_Array,
      Port_Image_Array => satellite_sys_send_photo_impl_Port_Image_Array,
      Address_Array => satellite_sys_send_photo_impl_Address_Array,
      Overflow_Protocol_Array => satellite_sys_send_photo_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => satellite_sys_send_photo_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.controller_process_photo_send_K,
      Thread_Port_Kinds => satellite_sys_photo_send_Port_Kinds,
      Has_Event_Ports => False,
      Thread_Port_Images => satellite_sys_photo_send_Port_Images,
      Thread_Fifo_Sizes => satellite_sys_photo_send_FIFO_Sizes,
      Thread_Fifo_Offsets => satellite_sys_photo_send_Offsets,
      Thread_Overflow_Protocols => satellite_sys_photo_send_Overflow_Protocols,
      Urgencies => satellite_sys_photo_send_Urgencies,
      Global_Data_Queue_Size => satellite_sys_photo_send_Total_FIFO_Size,
      N_Destinations => satellite_sys_photo_send_N_Destinations,
      Destinations => photo_send_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => satellite_sys_photo_send_Task.Next_Deadline);

  --  Periodic task : photo_send

  ----------------------------------
  -- satellite_sys_photo_send_Job -- 
  ----------------------------------

  function satellite_sys_photo_send_Job return PolyORB_HI.Errors.Error_Kind is
    photo_in_V : PolyORB_HI_Generated.Types.photo_data;
    photo_out_V : PolyORB_HI_Generated.Types.photo_data;
    Error_Ü : PolyORB_HI.Errors.Error_Kind;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    if (satellite_sys_photo_send_Interrogators.Get_Count
     (photo_in)
      /= -1)
    then
      photo_in_V :=
       satellite_sys_photo_send_Interrogators.Get_Value
         (photo_in).photo_in_DATA;
    else
      photo_in_V :=
       PolyORB_HI_Generated.Types.photo_data_Default_Value;
    end if;
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.satellite_sys_send_photo_spg
     (photo_in => photo_in_V,
      photo_out => photo_out_V);
    --  Set the call sequence OUT port values
    satellite_sys_photo_send_Interrogators.Put_Value
     (satellite_sys_send_photo_impl_Interface'
       (Port => photo_out,
        photo_out_DATA => photo_out_V));
    --  Send the call sequence OUT port values
    Error_Ü :=
     satellite_sys_photo_send_Interrogators.Send_Output
       (photo_out);
    if (Error_Ü
      /= PolyORB_HI.Errors.Error_None)
    then
      return Error_Ü;
    end if;
    --  Return error code
    return Error_Ü;
  end satellite_sys_photo_send_Job;

  --  BEGIN: Data types used by all instances of component get_photo.impl

  type satellite_sys_get_photo_impl_Integer_Array is
   array (satellite_sys_get_photo_impl_Port_Type)
     of Standard.Integer;

  type satellite_sys_get_photo_impl_Port_Kind_Array is
   array (satellite_sys_get_photo_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Controller_Process_satellite_sys_get_photo_impl_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Controller_Process_1_Max_Port_Image_Size);

  type satellite_sys_get_photo_impl_Port_Image_Array is
   array (satellite_sys_get_photo_impl_Port_Type)
     of UT_Activity_Controller_Process_satellite_sys_get_photo_impl_Port_Image_Array_Component;

  type satellite_sys_get_photo_impl_Address_Array is
   array (satellite_sys_get_photo_impl_Port_Type)
     of System.Address;

  type satellite_sys_get_photo_impl_Overflow_Protocol_Array is
   array (satellite_sys_get_photo_impl_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component get_photo.impl

  satellite_sys_photo_trigger_Port_Kinds : constant satellite_sys_get_photo_impl_Port_Kind_Array :=
   (photo_trigger_in =>
     PolyORB_HI.Port_Kinds.In_Event_Port,
    photo_trigger_out =>
     PolyORB_HI.Port_Kinds.Out_Event_Port);

  satellite_sys_photo_trigger_Port_Images : constant satellite_sys_get_photo_impl_Port_Image_Array :=
   (photo_trigger_in =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_photo_trigger_in_K),
    photo_trigger_out =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_photo_trigger_out_K));

  satellite_sys_photo_trigger_FIFO_Sizes : constant satellite_sys_get_photo_impl_Integer_Array :=
   (photo_trigger_in =>
     16,
    photo_trigger_out =>
     -1);

  satellite_sys_photo_trigger_Offsets : constant satellite_sys_get_photo_impl_Integer_Array :=
   (photo_trigger_in =>
     1,
    photo_trigger_out =>
     0);

  satellite_sys_photo_trigger_Overflow_Protocols : constant satellite_sys_get_photo_impl_Overflow_Protocol_Array :=
   (photo_trigger_in =>
     PolyORB_HI.Port_Kinds.Dropoldest,
    photo_trigger_out =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  satellite_sys_photo_trigger_Urgencies : constant satellite_sys_get_photo_impl_Integer_Array :=
   (photo_trigger_in =>
     0,
    photo_trigger_out =>
     0);

  satellite_sys_photo_trigger_Total_FIFO_Size : constant Standard.Integer :=
   16;

  satellite_sys_photo_trigger_N_Destinations : constant satellite_sys_get_photo_impl_Integer_Array :=
   (photo_trigger_in =>
     0,
    photo_trigger_out =>
     0);

  photo_trigger_Destinations : constant satellite_sys_get_photo_impl_Address_Array :=
   (photo_trigger_in =>
     System.null_Address,
    photo_trigger_out =>
     System.null_Address);

  package satellite_sys_photo_trigger_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => satellite_sys_get_photo_impl_Port_Type,
      Integer_Array => satellite_sys_get_photo_impl_Integer_Array,
      Port_Kind_Array => satellite_sys_get_photo_impl_Port_Kind_Array,
      Port_Image_Array => satellite_sys_get_photo_impl_Port_Image_Array,
      Address_Array => satellite_sys_get_photo_impl_Address_Array,
      Overflow_Protocol_Array => satellite_sys_get_photo_impl_Overflow_Protocol_Array,
      Thread_Interface_Type => satellite_sys_get_photo_impl_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.controller_process_photo_trigger_K,
      Thread_Port_Kinds => satellite_sys_photo_trigger_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => satellite_sys_photo_trigger_Port_Images,
      Thread_Fifo_Sizes => satellite_sys_photo_trigger_FIFO_Sizes,
      Thread_Fifo_Offsets => satellite_sys_photo_trigger_Offsets,
      Thread_Overflow_Protocols => satellite_sys_photo_trigger_Overflow_Protocols,
      Urgencies => satellite_sys_photo_trigger_Urgencies,
      Global_Data_Queue_Size => satellite_sys_photo_trigger_Total_FIFO_Size,
      N_Destinations => satellite_sys_photo_trigger_N_Destinations,
      Destinations => photo_trigger_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => satellite_sys_photo_trigger_Task.Next_Deadline);

  --  Periodic task : photo_trigger

  -------------------------------------
  -- satellite_sys_photo_trigger_Job -- 
  -------------------------------------

  function satellite_sys_photo_trigger_Job return PolyORB_HI.Errors.Error_Kind is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Get the IN port values
    --  Dequeue the IN port values
    satellite_sys_photo_trigger_Interrogators.Next_Value
     (satellite_sys_get_photo_impl_Port_Type'
       (photo_trigger_in));
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.satellite_sys_get_photo_spg;
    --  Return error code
    return Error_Ü;
  end satellite_sys_photo_trigger_Job;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return satellite_sys_alt_reader_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_read_altitude_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_reader_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_reader_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
   return satellite_sys_read_altitude_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_reader_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_reader_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_reader_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_reader_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_read_altitude_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_reader_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_read_altitude_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_reader_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out satellite_sys_read_altitude_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_reader_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return satellite_sys_alt_controller_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_altitude_controll_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_controller_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_controller_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
   return satellite_sys_altitude_controll_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_controller_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_controller_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_controller_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_alt_controller_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_altitude_controll_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_controller_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_altitude_controll_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_controller_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out satellite_sys_altitude_controll_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_alt_controller_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return satellite_sys_photo_send_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_send_photo_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_send_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_send_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
   return satellite_sys_send_photo_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_send_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_send_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_send_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_send_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_send_photo_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_send_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_send_photo_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_send_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out satellite_sys_send_photo_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_send_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return satellite_sys_photo_trigger_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_get_photo_impl_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_trigger_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_trigger_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
   return satellite_sys_get_photo_impl_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_trigger_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_trigger_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_trigger_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return satellite_sys_photo_trigger_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : satellite_sys_get_photo_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_trigger_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : satellite_sys_get_photo_impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_trigger_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out satellite_sys_get_photo_impl_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    satellite_sys_photo_trigger_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

end PolyORB_HI_Generated.Activity;
