--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated.Types;

package PolyORB_HI_Generated.Subprograms is

  procedure satellite_sys_send_photo_spg
   (photo_in : PolyORB_HI_Generated.Types.photo_data;
    photo_out : out PolyORB_HI_Generated.Types.photo_data);

  procedure satellite_sys_get_photo_spg;

end PolyORB_HI_Generated.Subprograms;
