--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated;
with PolyORB_HI.Marshallers_G;
pragma Elaborate_All (PolyORB_HI.Marshallers_G);

package body PolyORB_HI_Generated.Marshallers is

  --  Marshallers for interface type of thread send_photo.impl

  --------------
  -- Marshall -- 
  --------------

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.satellite_sys_send_photo_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Activity;
  begin
    if (Data.Port
      = PolyORB_HI_Generated.Activity.photo_out)
    then
      PolyORB_HI_Generated.Marshallers.Marshall
       (Data.photo_out_DATA,
        Message);
    end if;
  end Marshall;

  ----------------
  -- Unmarshall -- 
  ----------------

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.satellite_sys_send_photo_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.satellite_sys_send_photo_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type)
  is
    photo_in_DATA : PolyORB_HI_Generated.Types.photo_data;
    use PolyORB_HI_Generated.Activity;
  begin
    if (Port
      = PolyORB_HI_Generated.Activity.photo_in)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (photo_in_DATA,
        Message);
      Data :=
       PolyORB_HI_Generated.Activity.satellite_sys_send_photo_impl_Interface'
         (Port => PolyORB_HI_Generated.Activity.photo_in,
          photo_in_DATA => photo_in_DATA);
    end if;
  end Unmarshall;

  --  Marshallers for DATA type photo_data

  package photo_data_Marshallers is
   new PolyORB_HI.Marshallers_G
     (PolyORB_HI_Generated.Types.photo_data);

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.photo_data;
    Message : in out PolyORB_HI.Messages.Message_Type)
   renames photo_data_Marshallers.Marshall;

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.photo_data;
    Message : in out PolyORB_HI.Messages.Message_Type)
   renames photo_data_Marshallers.Unmarshall;

  --  Marshallers for interface type of thread get_photo.impl

  --------------
  -- Marshall -- 
  --------------

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.satellite_sys_get_photo_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type)
  is
    pragma Unreferenced
     (Message);
    pragma Unreferenced
     (Data);
  begin
    null;
  end Marshall;

  ----------------
  -- Unmarshall -- 
  ----------------

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.satellite_sys_get_photo_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.satellite_sys_get_photo_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type)
  is
    pragma Unreferenced
     (Message);
    use PolyORB_HI_Generated.Activity;
  begin
    if (Port
      = PolyORB_HI_Generated.Activity.photo_trigger_in)
    then
      Data :=
       PolyORB_HI_Generated.Activity.satellite_sys_get_photo_impl_Interface'
         (Port => PolyORB_HI_Generated.Activity.photo_trigger_in);
    end if;
  end Unmarshall;

end PolyORB_HI_Generated.Marshallers;
