--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with photo;

package body PolyORB_HI_Generated.Subprograms is

  procedure satellite_sys_send_photo_spg
   (photo_in : PolyORB_HI_Generated.Types.photo_data;
    photo_out : out PolyORB_HI_Generated.Types.photo_data)
   renames photo.send_photo;

  procedure satellite_sys_get_photo_spg
   renames photo.get_photo;

end PolyORB_HI_Generated.Subprograms;
