--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type photo_data is
   new Standard.Integer;

  --  photo_data'Object_Size ~= 32 bits

  photo_data_Default_Value : constant photo_data :=
   0;

end PolyORB_HI_Generated.Types;
